import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import '@/components/navigation/header/header.css'
import Header from '@/components/navigation/header/Header'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
import HeaderPage from '@/components/navigation/header/Header'
import React, { Children, FC, Suspense } from 'react'
import Provider from '@/components/provider/provider'
import { Loading } from '@/components/preferences/loading/LoadingUi'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Suspense fallback={<Loading />}>
                    <Provider>{children}</Provider>
                </Suspense>
            </body>
        </html>
    )
}
